---
- name: Deploy WordPress using Docker
  hosts: webserver
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Pull WordPress Docker image
      docker_image:
        name: wordpress
        source: pull

    - name: Pull MySQL Docker image
      docker_image:
        name: mysql:5.7
        source: pull

    - name: Create MySQL container
      docker_container:
        name: mysql
        image: mysql:5.7
        restart_policy: always
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_RANDOM_ROOT_PASSWORD: '1'

    - name: Create WordPress container
      docker_container:
        name: wordpress
        image: wordpress
        restart_policy: always
        ports:
          - "8080:80"
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
        links:
          - mysql